# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 911dc123db35354e9e12526a7e25f9434154b80c1ed3b1aeeafa003607c7c10325d777a9ba861cb9cd3049ed7875cb24371d6037baf2b306448e38668108450c

test:
  secret_key_base: 550868100333f62f023e411e7f37e431496a15b3b0d9af3a0cb6f7bb2cde2397b46d19d96b4a24ffa4cafe5e04ad5eac9750d7964efa2010362a354e18193963

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
